# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beb45f39d0d492fba04c93ac6dec121d24365c0677a8264969391d31204991f551b7adf910348994fe9734768624cab6e8a3ec2a02b59bb809daca46d1159013

test:
  secret_key_base: d4d8be88ca2c8407a2f65d095dd9b24cd008e72f875d74d7f6e641f148b31d7fc5782d357b402bff640a940a9e7888e4d601e9f5b65a6115e645a0c4e7d49f55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
